spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # publisher-confirms和publisher-returns是对于消息生产端的配置
    publisher-confirms: true # 开启发送消息确认 对应RabbitTemplate.ConfirmCallback接口
    publisher-returns: true  # 开启发送消息失败返回 对应RabbitTemplate.ReturnCallback接口

    # 这个配置是针对消息消费端的配置
    listener:
      direct:
        acknowledge-mode: manual # 开启 ack 手动确认
      simple:
        acknowledge-mode: manual # 开启 ack 手动确认
